AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Pokemon Card Scanner API

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        MODEL_VERSION: v1

Resources:
  PokemonCardFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        PredictApi:
          Type: Api
          Properties:
            Path: /predict
            Method: post
    Metadata:
      DockerTag: python3.11-v1
      DockerContext: ../lambda
      Dockerfile: Dockerfile

Outputs:
  PokemonCardApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/predict/"
  PokemonCardFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt PokemonCardFunction.Arn
